class DateFormat {
  static ANNOUNCEMENT_EXPIRY_DATE = 'MMM DD, YYYY'
  static CREATED_NOTE_DATE_TIME_FORMAT = 'MMMM D, YYYY h:'
  static THREAD_MODIFIED_DATE_FORMAT = 'MMM D, YYYY'
  static DOWNLOAD_ATTACHMENT_DATE_FORMAT = 'DDMMYYYY'
  static EDIT_ANNOUNCEMENT_EXPIRY_DATE = 'YYYY-MM-DD'
  static TRAINING_REPORT_FILTER = 'YYYY-MM-DD'
  static CREATE_FOLDER_FACILITATOR_RESOURCE_DATE_FORMAT = 'MMMM D, YYYY'
  static ACTIVITY_LOG_DATE_FORMAT = 'DD MMM, YYYY'
}

export default DateFormat
