class Story {
  static activityCommunities = 'Activity Log - Communities'
  static activityLog = 'Activity Log'
  static activityLogConnections = 'Activity Log - Connections'
  static activityLogConsent = 'Activity Log - Consent'
  static activityLogLearningAdmin = 'Activity Log - Learning Administration'
  static activityLogSecurity = 'Activity Log - Security'
  static activityTrainingAndDevelopment = 'Activity Log - Training & Development'
  static addRemoveMemberAndTeamLeader = 'Add/Remove Members and Team Leaders'
  static adminArticleCreateWithoutVideo = 'Admin - Article - Create without video'
  static adminArticleCreateWithVideo = 'Admin - Article - Create with Video'
  static adminArticleFileStructureAccessibility = 'Admin - Article - File Structure & Accessibility'
  static adminArticleList = 'Admin - Article list'
  static adminArticlePromotedHelpGuide = 'Admin - Article - Promoted Help Guide'
  static adminArticleVerifyCreation = 'Admin - Article - Verify Creation'
  static adminArticleCreateWithOrganizationVisibility =
    'Admin - Article - Create with Organization Visibility'
  static adminBanner = 'Admin - Banner'
  static adminTopicsRoles = 'Admin - Topics & Roles'
  static bookingCourse = 'Booking course'
  static communityManageMembers = 'Community Manage Members'
  static communityMemberShipRequests = 'Community Membership Requests'
  static communitySettings = 'Community Settings'
  static communityVisibility = 'Community Visibility'
  static consents = 'Consents'
  static copDiscussionNotificationOCoP = 'CoP Discussion Notification - OCoP'
  static courseAnnouncementAdminSite = 'Course Announcements - Admin Site'
  static courseAnnouncementLearnerSite = 'Course Announcements - Learner Site'
  static courseCatalog = 'Course Catalog'
  static courseCertificate = 'Course Certificate'
  static courseInstance = 'Course instance'
  static courseProgressCertificate = 'Course Progress and Certificates'
  static discussion = 'Discussion'
  static discussionAdminSite = 'Discussion - Admin Site'
  static enableDisableCommunityCourseCreation = 'Enable/Disable Community Course Creation'
  static fileSettingsShareToFolders = 'File Settings - Share-to Folders'
  static generalSettingAccountPasswordAndEmail = 'General Settings - Account password and email'
  static generalSettingLanguage = 'General Settings - Language'
  static generalSettingTimezone = 'General Settings - Timezone'
  static globalSearchFileAndFolder = 'Global Search File And Folder'
  static homeArticleDetailRelatedArticles = 'Home - Article Detail & Related Articles'
  static homeBannerArticleList = 'Home - Banner & Article list'
  static homeSearchFilter = 'Home - Search & Filtering'
  static ipsMigration = 'IPS Migration'
  static learner = 'Learner'
  static learnerPermission = 'Learner Permission'
  static learningPaths = 'Learning Paths'
  static lmsAdminManageConsent = 'LMS Admin - Manage Consent'
  static lmsAdminTrainingReports = 'LMS Admin - Training Reports'
  static lmsChangeLogActivityLibrary = 'LMS Change Log - Activity Library'
  static lmsChangeLogCertificate = 'LMS Change Log - Certificate'
  static lmsChangeLogCourse = 'LMS Change Log - Course'
  static lmsChangeLogCourseActivities = 'LMS Change Log - Course Activities'
  static lmsChangeLogCourseInstance = 'LMS Change Log - Course Instance'
  static lmsChangeLogLearningPath = 'LMS Change Log - Learning Path'
  static manageCommunities = 'Manage Communities'
  static orgAdminManageConsents = 'Org Admin - Manage Consents'
  static manageCourse = 'Manage Course'
  static manageCourseInstance = 'Manage Course Instance'
  static manageLearningPaths = 'Manage Learning Paths'
  static manageFile = 'Manage File'
  static manageFileOnlyOffice = 'Manage File - OnlyOffice'
  static manageFileStorageAndBandwidth = 'Manage File - Storage and Bandwidth'
  static manageFileRecycleBin = 'Manage File - Recycle Bin'
  static fileSettingsVault = 'File Settings - Vault'
  static manageStorage = 'Manage Storage'
  static manageUsers = 'Manage Users'
  static manageUsersMemberSecurity = 'Manage Users - Member Security'
  static manageUsersMembersProfileEncryption = 'Manage Users - Members profile + Encryption'
  static manageUsersOrganizationMemberProfile = 'Manage Users - Organization member profile'
  static myLearningFilter = 'My Learning Filter'
  static notes = 'Notes'
  static notificationsCommentPost = 'Notifications - Comment Post'
  static notificationsConsent = 'Notifications - Consent'
  static notificationsCreateAPost = 'Notification - Create a Post'
  static notificationsLearning = 'Notifications - Learning'
  static notificationsLikePost = 'Notifications - Like Post'
  static notificationsSharePost = 'Notifications - Share Post'
  static orgCoPDiscussionNotification = '[Org CoP] CoP Discussion Notification'
  static organizationActivityLibrary = 'Organization Activity Library'
  static organizationCourseInstanceActivities = 'Organization Course Instance Activities'
  static permissionOrgGlobalMenu = 'Permission Org Global Menu'
  static profileCommunityTab = 'Profile community tab'
  static profileConnection = 'Profile connection'
  static profileContactInfo = 'Profile contact info'
  static profileDetailInfo = 'Profile detail info'
  static profileGlobalSearchSetting = 'Profile global search setting'
  static profilePicture = 'Profile picture'
  static profileVisibility = 'Profile visibility'
  static recommendationHelpGuide = 'Recommendation Help guide'
  static resetPassword = 'Reset Password'
  static resources = 'Resources'
  static settings = 'Settings'
  static supportFileUploadVersion = 'Support File Upload Version'
  static trainingReport = 'Training Report'
  static tCopActivityLibrary = 'TCoP Activity Library'
  static twoStepAuthSetupAndConfiguration = '2SV Setup and Configuration'
  static unitInfo = 'Unit Info'
  static whiteLabelEmailNotifications = 'White label - Email Notification - Organization'
  static zoomSettings = 'Zoom Settings'
  static storyUnitInfo = 'Unit info'
  static orgUnitManageMembers = 'Org Unit - Manage Members'
  static helpGuidesAdminFileStructureAndAccessibility =
    'Admin - Article - File Structure & Accessibility'
  static ticket(testCaseId = '', bugIds = []) {
    const allure = Cypress.Allure.reporter.getInterface()
    const jiraUrl = 'https://khalibre.atlassian.net/browse/'
    if (testCaseId) {
      allure.link(jiraUrl + testCaseId, 'Test Case: ' + testCaseId, 'tms')
    }
    if (bugIds.length) {
      bugIds.forEach((id) => {
        allure.link(jiraUrl + id, 'Bug: ' + id, 'issue')
      })
    }
  }
}

export default Story
