export const Lms = {
  learningPath: 'Learning Path',
  courseCatalog: 'Course Catalog',
  course: 'Course',
  microLearning: 'Micro-Learning',
  languages: 'Languages',
  categoriesCommunities: 'Categories/Communities',
  germanLanguage: 'German',
  frenchLanguage: 'French',
  chineseLanguage: 'Chinese',
  polishLanguage: 'Polish',
  fireCloudZone: 'FireCloud Zone',
  courseTypes: 'Course Types',
  community: 'Community',
  createAnInstance: 'Create an instance',
  instanceOverview: 'Instance Overview',
  editInstance: 'Edit Instance',
  publicLibrary: 'Public library',
  organizationLibrary: 'Organization library',
  addToActivityLibrary: 'Add to activity library',
  activityLibrary: 'Activity Library',
  standardActivity: 'Standard activity',
  activityTemplate: 'Activity template',
}
