//Done in UAT

import './add-new-org-member/add_cop_admin_has_connection.cy'

import './add-connection/cop_admin_add_connection_to_amanda.cy'
import './add-connection/cop_admin_add_connection_to_jamison.cy'

import './create-cop/create_mwcop_func_for_accept_deny_web.cy'
import './create-cop/create_mwcop_func_for_accept_email.cy'
import './create-cop/create_mwcop_func_for_accept_home.cy'
import './create-cop/create_mwcop_func_for_deleting.cy'
import './create-cop/create_mwcop_func_for_invitation.cy'
import './create-cop/create_mwcop_func_for_reminder.cy'
import './create-cop/create_ocop_func_for_accept_deny_web.cy'
import './create-cop/create_ocop_func_for_accept_email.cy'
import './create-cop/create_ocop_func_for_accept_home.cy'
import './create-cop/create_ocop_func_for_deleting.cy'
import './create-cop/create_ocop_func_for_invitation.cy'
import './create-cop/create_ocop_func_for_reminder.cy'
import './create-cop/create_tcop_func_for_accept_deny_web.cy'
import './create-cop/create_tcop_func_for_accept_email.cy'
import './create-cop/create_tcop_func_for_accept_home.cy'
import './create-cop/create_tcop_func_for_deleting.cy'
import './create-cop/create_tcop_func_for_invitation.cy'
import './create-cop/create_tcop_func_for_reminder.cy'
import './create-cop/create_tpcop_func_for_accept_deny_web.cy'
import './create-cop/create_tpcop_func_for_accept_email.cy'
import './create-cop/create_tpcop_func_for_accept_home.cy'
import './create-cop/create_tpcop_func_for_deleting.cy'
import './create-cop/create_tpcop_func_for_invitation.cy'
import './create-cop/create_tpcop_func_for_reminder.cy'

import './create-cop/create_mwcop_func_for_assign_role.cy'
import './create-cop/create_ocop_func_for_assign_role.cy'
import './create-cop/create_tcop_func_for_assign_role.cy'
import './create-cop/create_tpcop_func_for_assign_role.cy'

import './create-quick-post/quick_post_on_mwcop_accept_email.cy'
import './create-quick-post/quick_post_on_mwcop_accept_home.cy'
import './create-quick-post/quick_post_on_ocop_accept_email.cy'
import './create-quick-post/quick_post_on_ocop_accept_home.cy'
import './create-quick-post/quick_post_on_tcop_accept_email.cy'
import './create-quick-post/quick_post_on_tcop_accept_home.cy'
import './create-quick-post/quick_post_on_tpcop_accept_email.cy'
import './create-quick-post/quick_post_on_tpcop_accept_home.cy'
