// Done setup on UAT

import './create-course/course_func_retake.cy'
import './create-course/course_func_withdraw.cy'
import './create-course/course_func_withdraw_notification.cy'
import './create-course/progress_on_disable_certificate.cy'
import './create-course/progress_on_enable_certificate.cy'
import './create-course/progress_on_mix_activities.cy'

import './course-instance/award_certificate.cy'
import './course-instance/elearning_file_feedback.cy'
import './course-instance/instance_complete_retake.cy'
import './course-instance/instance_in_progress_course.cy'
import './course-instance/instance_never_withdraw.cy'
import './course-instance/instance_new_course.cy'
import './course-instance/instance_withdraw_notify.cy'
import './course-instance/not_award_certificate.cy'
import './course-instance/two_elearning_quiz.cy'
import './course-instance/video_elearning_assignment.cy'

import './add-activity-to-instance/activity_file_to_disable_certificate_instance.cy'
import './add-activity-to-instance/activity_file_to_enable_certificate_instance.cy'
import './add-activity-to-instance/activity_reasons_workout_to_new_instance.cy'
import './add-activity-to-instance/activity_reasons_workout_to_progress_instance.cy'
import './add-activity-to-instance/activity_toactivity_image_to_instance.cy'
import './add-activity-to-instance/activity_toactivity_image_to_retake_instance.cy'
import './add-activity-to-instance/elarning_file_feedback_to_instance.cy'
import './add-activity-to-instance/two_elarning_quiz_to_instance.cy'
import './add-activity-to-instance/video_elarning_assignment_to_instance.cy'
