export const ComSharingConstant = {
  ALLOW_DUPLICATE: 'Allow duplicate',
  ALLOW_DUPLICATE_DISABLED: 'Allow duplication is disabled.',
  ALLOW_DUPLICATE_ENABLED: 'Allow duplication is enabled.',
  ALL_COURSE_INSTANCES: 'All course instances',
  APPROVED: 'Approved',
  COMMUNITY_SHARING: 'Community Sharing',
  PENDING: 'Pending',
  REQUIRE_PERMISSION: 'Require permission',
  REQUIRE_PERMISSION_DISABLED: 'Require permission is disabled.',
  REQUIRE_PERMISSION_ENABLED: 'Require permission is enabled.',
  SHARED_COURSE_DISABLED: 'Shared course is disabled.',
  SHARED_COURSE_ENABLED: 'Shared course is enabled.',
  SPECIFIC_COURSE_INSTANCES: 'Specific course instances',
  SUGGEST: 'Suggest',
  SUGGESTED: 'Suggested',
  SUGGEST_TO_COMMUNITY: 'Suggest to Communities',
  COMMUNITY_SHARING_UPDATED: 'Community Sharing has been updated.',
}
