export const ModifyCourseConstant = {
  ACCESS: 'Access',
  ACCOUNT: 'Account',
  ACCOUNT_CODE: 'Account Code',
  ADD_A_COURSE_IMAGE: 'Add a Course Image',
  ALLOW_ADDING_PROFILE: 'Allow adding to profile',
  ALL_LEARNERS_IN_COURSE: 'All learners in this course',
  AWARD_LEARNERS_WITH_CERTIFICATE: 'Award learners with a certificate',
  CATEGORIES: 'Categories',
  CATEGORY: 'Category',
  CHANGE_PHOTO: 'Change Photo',
  COLLABORATION_SETTINGS: 'Collation Settings',
  CONNECT_IS_A_DIRECTORY_FOR_LEARNER:
    'Connect is a directory for learners that enables them to engage with others who are taking this course.',
  COURSE_COMPLETIONS: 'Course Completion',
  COURSE_FEE: 'Course Fee',
  COURSE_OVERVIEW: 'Course Overview',
  COURSE_TITLE: 'Course Title',
  ENABLE_CONNECT: 'Enable Connect',
  ENABLE_DISCUSSION: 'Enable Discussions',
  ENTER_CATEGORY: 'Enter Category',
  ENTER_THE_TITLE_OF_COURSE: 'Enter the title of the course',
  MEMBERS_FROM_SELECTED_CATEGORIES_CAN_ACCESS:
    'Members from selected categories can access and book this course. Category admins can also manage this course.',
  NOTE_THESE_FILES_AVAILABLE_EVERYONE:
    'Note: These files will be available for everyone (including pre-booking)',
  ONLY_LEARNERS_IN_SAME_INSTANCE: 'Only learners within the same course instance',
  PAYMENT_METHOD: 'Payment Method',
  POSTPAID: 'Postpaid',
  PREPAID: 'Prepaid',
  PROVIDE_A_FORUM_FOR_LEARNERS:
    'Provide a forum for learners and facilitators to post and have conversations.',
  SAVE_AS_DRAFT: 'Save as Draft',
  SAVE_Course: 'Save Course',
  SECOND_ACCOUNT: 'Second Account',
  SELECT_FILES: 'Select Files',
  UPLOAD_FILE: 'Upload File',
  USD: 'USD',
  WHO_LEARNERS_CAN_SEE: 'Who learners can see',
}
