export const CreationInstanceLabel = {
  INSTANCE_TITLE: 'Instance Title',
  FACILITATORS: 'Facilitators',
  ADD_FACILITATOR: 'Add Facilitator',
  LANGUAGE: 'Language',
  COURSE_COMPLETION: 'Course Completion (days)',
  EXPECTED_DURATION: 'Expected Duration (minutes)',
  TIME_ZONE: 'Time Zone',
  START_DATE: 'Start Date',
  END_DATE: 'End Date',
  MAX_PARTICIPANTS: 'Maximum Number of Participants',
  MUST_BOOK_BY: 'Must Book by',
  MUST_CANCEL_BY: 'Must Cancel by',
  COURSE_CONTACT_EMAIL: 'Course Contact Email',
  ADDITIONAL_NOTE: 'Additional Booking Note',
  NOTE: 'Note: This fee will be used instead of the price you set on the course level.',
  SAVE_INSTANCE: 'Save Instance',
  CANCEL: 'Cancel',
}
